version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: it-cons-postgres
    environment:
      POSTGRES_DB: it_cons
      POSTGRES_USER: it_cons
      POSTGRES_PASSWORD: it_cons
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
